// Assemble scripts/gallery/gallery.html from the captured shots. Pairs each
// tvOS state with its web reference (when one exists) for side-by-side gap
// review. Run after capture-tvos.sh (and optionally capture-web.mjs).
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { existsSync, writeFileSync, readdirSync } from 'node:fs';

const here = dirname(fileURLToPath(import.meta.url));
const tvosDir = join(here, 'shots', 'tvos');
const webDir = join(here, 'shots', 'web');

// Display order = a player's journey. Web ref shares the name except where the
// state is tvOS-only (no web equivalent in the harness).
const ORDER = [
  ['lobby', 'Lobby (4 players)'],
  ['lobby-2p', 'Lobby (2 players + empty slots)'],
  ['lobby-8p', 'Lobby (8 players)'],
  ['lobby-empty', 'Lobby (waiting)'],
  ['countdown', 'Countdown'],
  ['game', 'Game · Normal (Lv 1)'],
  ['game-lv8', 'Game · Pillow (Lv 8)'],
  ['game-lv12', 'Game · Neon (Lv 12)'],
  ['pause', 'Paused'],
  ['pause-music', 'Paused (music switch focused)'],
  ['disconnected-controller', 'Disconnected — one controller (per-board)'],
  ['reconnecting', 'Display reconnecting (full screen)'],
  ['disconnected-display', 'Display disconnected (full screen)'],
  ['results', 'Results'],
  ['results-solo', 'Results (solo)'],
];

const have = (dir, name) => existsSync(join(dir, `${name}.png`));
const rel = (dir, name) => `shots/${dir}/${name}.png`;

// Pick up any captured states not in ORDER, so nothing is silently dropped.
const known = new Set(ORDER.map(([k]) => k));
const extras = existsSync(tvosDir)
  ? readdirSync(tvosDir).filter(f => f.endsWith('.png')).map(f => f.replace(/\.png$/, '')).filter(k => !known.has(k))
  : [];
for (const k of extras) ORDER.push([k, k]);

const rows = ORDER.filter(([k]) => have(tvosDir, k) || have(webDir, k)).map(([key, title]) => {
  const web = have(webDir, key)
    ? `<figure><figcaption>web reference</figcaption><img loading="lazy" src="${rel('web', key)}"></figure>`
    : `<figure class="missing"><figcaption>web reference</figcaption><div class="none">no web equivalent</div></figure>`;
  const tv = have(tvosDir, key)
    ? `<figure><figcaption>tvOS</figcaption><img loading="lazy" src="${rel('tvos', key)}"></figure>`
    : `<figure class="missing"><figcaption>tvOS</figcaption><div class="none">not captured</div></figure>`;
  return `<section class="state"><h2>${title} <span class="key">${key}</span></h2><div class="pair">${web}${tv}</div></section>`;
}).join('\n');

const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>HexStacker tvOS — screen gallery</title>
<style>
  :root { color-scheme: dark; }
  * { box-sizing: border-box; }
  body { margin: 0; background: #15121f; color: #ece8f5;
    font: 15px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif; }
  header { padding: 28px 32px 8px; }
  header h1 { margin: 0 0 4px; font-size: 22px; letter-spacing: .02em; }
  header p { margin: 0; color: #9b93b4; }
  .legend { margin: 12px 32px 0; color: #9b93b4; font-size: 13px; }
  main { padding: 16px 32px 64px; display: flex; flex-direction: column; gap: 36px; }
  .state h2 { font-size: 16px; margin: 0 0 10px; font-weight: 600; letter-spacing: .02em; }
  .state h2 .key { color: #6f6790; font-weight: 400; font-size: 12px; margin-left: 8px;
    font-family: ui-monospace, SFMono-Regular, Menlo, monospace; }
  .pair { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; align-items: start; }
  figure { margin: 0; background: #1d1930; border: 1px solid #2c2742; border-radius: 12px; overflow: hidden; }
  figcaption { padding: 6px 10px; font-size: 12px; color: #9b93b4; border-bottom: 1px solid #2c2742;
    text-transform: uppercase; letter-spacing: .08em; }
  figure img { display: block; width: 100%; height: auto; background: #000; }
  figure.missing .none { display: grid; place-items: center; aspect-ratio: 16/9; color: #5c5578; font-style: italic; }
  @media (max-width: 900px) { .pair { grid-template-columns: 1fr; } }
</style></head>
<body>
<header>
  <h1>HexStacker tvOS — screen gallery</h1>
  <p>Web reference (left) vs native tvOS render (right). Regenerate after UI changes.</p>
</header>
<p class="legend">Generated by <code>scripts/gallery/gen-gallery.mjs</code>. tvOS shots: <code>capture-tvos.sh</code>. Web shots: <code>capture-web.mjs</code>.</p>
<main>
${rows}
</main>
</body></html>
`;

const out = join(here, 'gallery.html');
writeFileSync(out, html);
console.log('wrote', out);
